@urlDev=http://localhost:3051

### checkStatus

GET {{urlDev}}/checkstatus

### set user

PUT {{urlDev}}/v1/user
Content-Type: application/json

{
    "key": "u:10001",
    "payload": {
        "uid": "10001",
        "name": "quangdz.com"
    }
}

### 
POST  {{urlDev}}/v1/users
Content-Type: application/json

{
    "key": "u:10001"
}